### ISSUE TITLE
Dates are displayed in ENGLISH

### ISSUE THREAD

**Issue by Galixte** [oxpus/Basis-Statistics-32#2]
Hi @oxpus,

in FRENCH i have a problem with dates like ```june 2017``` which are displayed in english.

Could you make in sort to change the PHP code to display the dates in the language used on the board, please ?

I know it’s in ```main.php``` file but i didn’t find which part of code has to be fixed.

**Comment by oxpus** [comment]
The feed will read the post from the source and does not reformat it.
There's no function to format any date.
Can you please give an example?

**Comment by Galixte** [comment]
Same answer: https://github.com/oxpus/Basic-Statistics/issues/6#issuecomment-309632480 ;)

**Comment by oxpus** [comment]
Package fixed.
The month names shall now be formated within the user language.

**Comment by Galixte** [comment]
Thanks chief 👍
